### ISSUE TITLE
In results "ISP" should specify filter level

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#66] opened 2014-07-02 13:59 UTC
For example, in the case of BT - when it is checked against the "moderate" filter, the ISP should be listed like "BT (moderate)" instead of "BT".

This makes it clearer what setting blocks the site, and presumably would allow us to (in the future) run queries against different filters where suggested profiles are available.

**Comment by NetworksAreMadeOfString** [comment] 2014-07-02 14:03
We can only (feasibly) do this for probes under ORGs direct control or with a bullet proof canary list.

**Comment by gwire** [comment] 2014-07-02 14:05
In the case of BT, we _know_ the filter profile chose was "moderate" though, right?

**Comment by NetworksAreMadeOfString** [comment] 2014-07-02 14:08
But the API is open. In theory we could already have tens of 3rd party clients contributing from BT lines by now.

We'll need to alter (if not already done) the DB to add a "Filter Level" column and a lookup table (normalisation yay!)

**Comment by graphiclunarkid** [comment] 2014-07-02 14:33
I believe we can distinguish between ORG controlled and other probes already. We want to surface this distinction in the results (when the time is right to start including third-party results) and we'll make it clear we can't be certain about the filtering settings on third-party clients.

For the ORG probes I think this is a good idea. It'll be especially useful if we want to expand to running multiple probes per ISP ourselves so that we can compare results across all their filtering settings.

**Comment by dantheta** [comment] 2014-07-02 14:34
The filter_level column already exists, but there isn't code to accept
values for it yet.  It's free text at the moment (but that could change).  

We'll need to do a bit more research to create a canary list to
auto-categorize, and specify what and how a probe should use this list.

I wonder if we can interrogate the home hub itself ...

Daniel.

**Comment by dantheta** [comment] 2014-07-04 14:23
Is this a dupe of #74 (or vice-versa)?

**Closed as completed** 2014-07-09 10:50 UTC
Labels: enhancement
