### ISSUE TITLE
Add form field to opt into future blocked reports

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#23] opened 2014-06-03 16:22 UTC
Add field such as "Please email me regular blocking reports" If possible create email verification method.

**Comment by graphiclunarkid** [comment] 2014-06-03 16:29
Is this a duplicate of #6 or something different? Email verification method is #18.

**Comment by JimKillock** [comment] 2014-06-03 16:43
It's to collect the data for reports prior to the feature being available, if that makes sense?

**Comment by graphiclunarkid** [comment] 2014-06-09 18:11
Implemented in pull request openrightsgroup/blocked-org-uk#60 and available for checking on the http://stage.blocked.org.uk front page.

Probably needs @mkillock to do things with FormIt to make it actually work though.

**Comment by mkillock** [comment] 2014-06-09 19:28
1. The data comes through to the FormSave table OK, but the allowcontact, subscribereports  and joinlist fields are only present when the option is selected on the form. In other words, if the option is not selected there is no allowcontacts = no in the FormSave table. Is that a problem?
2. How do we want to handle Form submission? There was another ticket about checking for an email address if the subscribe tick is present - so presumably we want the form to refuse to submit if:
   (a) No url
   (b) No url, any combo ticks set and email blank

Right?
1. (this is actually point 3 - github modifies it to 1)  Do we want something different to happen depending on what ticks are set? e.g. send an email to a subscription system?

**Comment by graphiclunarkid** [comment] 2014-06-10 09:25
I think it would be better if we could record "XYZ = no" in the FormSave table because it would make future scripting easier. It's by no means essential though.

Does any data other than the URL get transferred to the API and its database?

Your point 2 is exactly right. Both openrightsgroup/blocked-org-uk#5 and openrightsgroup/blocked-org-uk#51 talk about what to do if a user doesn't specify an email address. I think the former can be closed since you've fixed the latter (it was an early comment and probably superseded by subsequent development).

With respect to your point 3, we will want different things to happen for each set checkbox, but for now it's enough to record in the database which options the visitor chose. I am meeting with @JimKillock and Pam tomorrow to discuss ORG's requirements for emailing things out from the system. I'll revise the existing set of issues about emailing after that discussion.

**Comment by graphiclunarkid** [comment] 2014-06-10 10:08
I've raised #27 to deal with recording the state of cleared checkboxes explicitly.

**Comment by mkillock** [comment] 2014-06-10 11:35
Everything gets passed to the API database, but the extra stuff (opt ins/stories/etc) goes into a single field as a string of items - If I understand it correctly.

I'll let you and Ruth decide whether to close the other issue!

I've added field=no to the formsave stuff, will update #27

**Comment by graphiclunarkid** [comment] 2014-06-10 11:59
Great stuff, thanks @mkillock. In that case I think we're done here.

**Closed as completed by graphiclunarkid** 2014-06-10 11:59 UTC
Labels: enhancement, in progress
