### ISSUE TITLE
AJAX results page

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#25] opened 2014-06-09 10:51 UTC
Since test results are only taking a few seconds to return, we could push them into the results page using AJAX so that they populate "live", rather than only displaying historical results from the database.

This would prevent people submitting URLs for testing twice just to see the results of their first check on-screen.

This would also reduce the need to email results to people, meaning we can shift the focus of the email system onto sending regular reports, and it wouldn't matter if we delayed implementing email post-launch. Handy since we haven't yet agreed the high-level requirements for the email system!

**Comment by dantheta** [comment] 2014-06-09 16:22
I have a demo of this that uses a long poll http requests and blocks on the amqp results queue :)

**Comment by graphiclunarkid** [comment] 2014-06-09 17:19
:sunglasses:

**Comment by dantheta** [comment] 2014-06-23 11:44
I've committed an example page in the Blocking-Middleware repo, which uses a new API endpoint to get realtime results from the probes. (example-client/example-realtime.php).  Although the file extension is .php, there is only HTML in there.  It uses an iframe for now because I'm old-school, and because my javascript isn't quite up to getting incremental data from another page.

The script called inside the iframe is a standard helper script that wraps the API call, to make sure that the API user's key stays secret.  The helper script reads json result stanzas from the API, which is transmitting them in one response using chunked encoding, so that it can be read incrementally.

Someone with greater javascript talents may be able to adapt the helper script to emit the data in the right format for a more javascripty solution.

In the meantime there's a demo here:

http://www.dretzq.org.uk/org-live/example-realtime.php

**Comment by graphiclunarkid** [comment] 2014-06-24 00:22
Wow - that's awesome! Definitely want to get this in as an enhancement!

**Comment by Polarisation** [comment] 2014-10-22 18:54
At the ORG hack day we put together a javascript function, which along with a PHP helper script and some backend changes, provides realtime updates in the seconds after the page loads.

Here's what needs doing to complete this:
1. We need to change the results page so that it always includes the table. Currently if the page displays before any results are ready, there will be no table. Without the table on the page, the JavaScript doesn't work. I believe there is also a message about no results which would also need editing / removing.
2. We need to include the JavaScript on the results page. I've edited the JavaScript function to work on the live site:
   https://gist.github.com/Polarisation/fc6d8155dbe559a2512e
3. (optional) Add CSS which highlights the changes to the table to the user (each rows will flash yellow for half a second after it updates). https://gist.github.com/Polarisation/c778a4b399654ab2841e

That should be all, and sorry for the delay! If we can find a way to get modx working with Git that would make this kind of work easier in future.

**Comment by graphiclunarkid** [comment] 2014-11-05 22:10
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Thanks so much for this, Justin! It's possible @mkillock can help out with implementation. Otherwise I will put it on my list of things to do.

Getting the PHP stuff into github is definitely on our wish list too. If you have any advice on how we might go about it that'd be great. I got as far as discovering the existence of 'static resources' before running out of time.

---

Project Manager
Open Rights Group

Support our work: https://www.openrightsgroup.org/join

Snet form my phone. Please esxuce bvretiy & tpyos.
-----BEGIN PGP SIGNATURE-----

iQJIBAEBCAAyKxxSaWNoYXJkIEtpbmcgPHJpY2hhcmRAcmljaGFyZHNraW5nZG9t
Lm5ldD4FAlRaoCsACgkQ8n2YfEiEnSgfyQ/+ImX9ZXSREnBV1Updpg0Rf6gh6Djl
sjUYQ6718rlfnDE65N/zVUyJyoOIiywvQID1SXMwDN8yY2u0hQ1fX8zKqZ8FG/1P
Zt1RsCUbjuT0qyFg5jUxPLcGiRwHUyrH9LSYSGeoU3yz8wTFSA8inCWkQT3ccJaK
q6/yXq5jR4O/nc1RldA8OhkORhJk4D4bsEWsJuAROy7gx3PC85+FluZJzThUVMz3
P94ydCVjWtV1erNK9Juk9PwmdVs5yTnj5PyO4bIjGE5ZeyDr1aXNbX9BV03vvlRH
8KOVKDz15BboLCp7FgLR9bKWE6g5X/IDujm8UaY9UatbNJfshM9nDgCXl2hi3IQK
bjjb9u6c401CPYaSECGUe1R70hgWQS1rCQiMFSk4UGQuklIN28Hw4rNQrAf8BT/I
sQyTLg7aoxgQTs84JrXWHvD6CU0lQUW7z4vUftsaJByiZr/N7XGvHKGYIcuCVUkS
9+nBKW6cqkIMmkJyUpxz5te7PLf3gBUBTr3TWNmK/o4TWiUTwhwvPCAfcO2I0Tqi
7flKyw+n1y3zXgYeDPP5xhVNqs6hORyH1/5fWqZiAcauAmGvKIQepiQapQt12ehk
t4k0c0bhewGDFodEymZXA5Wms5b0vZbdwdT/44dtK9Offpi0Op4Rww3VJ1kmAT+d
tCYTh5tg61f7Oyk=
=puAS
-----END PGP SIGNATURE-----

**Comment by mkillock** [comment] 2014-11-08 14:18
looking at this now

**Comment by mkillock** [comment] 2014-11-08 15:36
ok! I think this is done, except for the css - I attempted to upload a new main.css with the css included but this does not seem to have taken. Could someone with filesystem access edit this file to include the css linked to above please?

Changes:
1. edited blocked_head chunk to include a reference to the js, which is uploaded alongside other js under blocked assets tree
2. edited the OfferSubmission chunk to include a table, and edited the text slightly

Could someone tell me if it is working as intended please?

**Comment by mkillock** [comment] 2014-11-08 19:50
It's not working for some reason, the results are updating on the helper page but not showing in the table.

**Comment by Polarisation** [comment] 2014-11-10 21:25
OK, the problem is that this code depends on the jQuery library, but jQuery has been included in a rather strange fashion at the bottom of the page. This means jQuery has not loaded when the code attempts to run, so it fails.

To fix this, we need to move this line: 
    `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>`
... to above where the realtime results is included.

Sorry I missed this... normal practice would be to include jQuery right at the top, I didn't consider that it might have been done this way. I can't really see why it was included so far down the page... perhaps just because it was easier to plonk it there than to find the header snippet.

Regarding the CSS, it seems that was uploaded successfully... it was probably just that the browser had cached the old version.

**Comment by mkillock** [comment] 2014-11-10 21:47
Hi, no problem! Glad you can see what's wrong! I've moved that line - is it working now?

**Comment by graphiclunarkid** [comment] 2014-11-10 22:26
Worth noting that we run Varnish in front of MODx so changes sometimes don't show up immediately. I'm not sure if there's a way we can flush that cache as developers (@gwire might be able to comment though).

AIUI people sometimes include JS scripts last because they're loaded inline, so the browser blocks waiting for that to happen, which can slow down the appearance of the rest of the page if they appear too far up. I don't know whether that's the reason in this case - perhaps @webal might know?

**Comment by Polarisation** [comment] 2014-11-10 22:43
Yes it's working! At least in Firefox. It seems there's typically a delay with PlusNet and Vodafone, these get updated a few seconds after submitting a URL. I'll try out on some other browsers soon. 

There is one thing we should fix just in case... the javascript is being included on every page on the site, which causes an error on the other pages. It probably won't cause any noticeable issue, but just in case, please can we update the javascript to include this line to check we're on the right page:
     `if($('tabel#results').size())`
I've updated [the gist](https://gist.github.com/Polarisation/fc6d8155dbe559a2512e) so you can see where this goes.

**Comment by mkillock** [comment] 2014-11-10 22:54
I presume that should be table instead of tabel! I've uploaded a new js file but perhaps Varnish is stopping it from appearing yet.

What should I see if it is working? When I submit a new site, it does not update 3 seconds or so later with Vodafone. If I click on the permalink it shows Vodafone with a slightly later timestamp

**Comment by gwire** [comment] 2014-11-10 22:59
If you need assets purged from the cache on production, let me know.  I've gone ahead and purged /assets/site/blocked/\* - is that sufficient?

**Comment by dantheta** [comment] 2014-11-10 23:03
During development, temporarily appending "?s=1" to the JS URLs (and incrementing the number with each iteration) may temporarily bust the cache :)

**Comment by Polarisation** [comment] 2014-11-10 23:32
The test case I am using to see this work is www.example.com. This already has results, but they should update after re-submitting it. Most of the probes respond near-instantly so are updated when the page loads. PlusNet almost always updates later - it takes about 10 seconds, and you should see it flash yellow for about half a second when it does.

However I think I see some cases where it's not working as expected (failing silently). I'll take another look at this another evening this week.

**Comment by mkillock** [comment] 2014-11-11 07:49
Ah! Yes that url works me too. I had been trying various bogus urls which are DNS-fail causing errors. Perhaps that's as designed - to not bother updaing when the results are just errors?

**Comment by graphiclunarkid** [comment] 2014-11-19 18:47
This is looking really good now - especially after the cache-wrangling you did at the ORGCon14 hack-day :smile:

I'm afraid I've noticed a possible bug though.  I've raised it as #103.

**Comment by Polarisation** [comment] 2014-12-07 22:25
I've tidied this up, fixing a few bugs. We'll need to replace the old realtimeresults.js with the new one (now contained in Blocking-Middleware/example-client)

**Closed as completed** 2014-12-10 16:24 UTC
Labels: enhancement
