### ISSUE TITLE
static results pages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#12] opened 2014-05-28 09:36 UTC
(Not for initial release) It strikes me it would be helpful to produce URLs for results pages in the form https://result.blocked.org.uk/example.org

**Comment by JimKillock** [comment] 2014-05-30 16:27
See also request openrightsgroup/blocked-org-uk#7

**Comment by mkillock** [comment] 2014-06-10 09:32
We can do this fairly easily with the current set up, just need to pass in a $_GET parameter to the GetURLHistory snippet. Working example here:

http://stage.blocked.org.uk/results.html?url=www.example.com

**Comment by graphiclunarkid** [comment] 2014-06-10 12:25
That's pretty cool!

If someone visits a URL that has no results can we suggest they submit it for checking? Currently they arrive at a slightly out-of-context page, e.g.http://stage.blocked.org.uk/results.html?url=asdf.com

**Comment by mkillock** [comment] 2014-06-10 12:34
OK, done - when there are no previous results, it will use the OfferSubmission chunk instead.

Text and formatting can be changed easily in that chunk - again @webal may have some useful input here!

**Comment by graphiclunarkid** [comment] 2014-06-10 12:43
Perfect :smile:

**Comment by graphiclunarkid** [comment] 2014-06-11 15:10
This now needs some copy writing for it and final styling applying (@webal).

**Comment by webal** [comment] 2014-06-12 21:35
would it make sense to reuse the thank you page for this - it's pretty much the same function now - especially as the home page form goes straight to results?
If not I'll have a crack at styling once the content is in

**Comment by graphiclunarkid** [comment] 2014-06-12 21:46
It probably would, yes. That way we can capture sign-ups, reports, and other information from people landing on a static results page even if they weren't the original submitter.

**Comment by graphiclunarkid** [comment] 2014-06-23 05:59
On the live server, Modx seems to encode parameters when the URL is included in a page using `[[!+fi.domainToCheck]]`, such that

`http://new.blocked.org.uk/results?url=http://example.com/`

becomes

`https://new.blocked.org.uk/results?url=http%3A%2F%2Fexample.com%2F`

Only the latter seems to work - the former claims that no results are found in the database. I think we care about this because people are more likely to type and link to the first form of link than the second. Is there a difference between the dev and live Modx configuration that's causing it?

**Comment by graphiclunarkid** [comment] 2014-06-23 06:07
On the dev server the static URLs are of the form

`http://stage.blocked.org.uk/results.html?url=http://example.com`

Whereas on the live server they seem to be of the form

`http://new.blocked.org.uk/results?url=http://example.com` (note missing .html extension)

Does this matter?

@webal - if we're going to use the thankyou.html page for this purpose I think we should rename it to be results.html as that makes more sense for static URLs.

**Comment by mkillock** [comment] 2014-06-23 10:07
OK, if we combine thankyou and results pages then we need to implement the $_GET mechanism from the homepage form and switch off FormItRetriever - if that's what we're doing then I think that's possible but I would prefer to wait for confirmation about this choice before I make changes

@graphiclunarkid - I don't think results vs results.html matters - this is just an option in MODx FriendlyURLs implementation, which may be system wide so we can't change it. Perhaps we should change staging to match live?

I can't reproduce the HTML encoding issue - could you tell me what you did?

**Comment by graphiclunarkid** [comment] 2014-06-29 18:43
@mkillock I can't think of a good reason for having separate pages for results that are shown after submitting a URL on the homepage and results shown by visiting a static URL. The only thing that does is give us two pages to maintain and prevent people who arrive directly on the site from filling in the form to subscribe for alerts etc.

The HTML encoding issue isn't. In fact it's a problem with this page thinking there's a difference between URLs with a trailing '/' and those without. Compare:

https://new.blocked.org.uk/results?url=https://richardskingdom.net
https://new.blocked.org.uk/results?url=https%3A%2F%2Frichardskingdom.net

with

https://new.blocked.org.uk/results?url=https://richardskingdom.net/
https://new.blocked.org.uk/results?url=https%3A%2F%2Frichardskingdom.net%2F

**Comment by graphiclunarkid** [comment] 2014-06-30 14:53
For launch @jimkillock is going to duplicate the page content from /results into the page that gets displayed when someone visits /resurlts?url=whatever. This requires minimal work and the pages will then appear the same to visitors.

Post-launch we should look into making them the same modx resource as then we won't have to remember to make changes in both places.

**Comment by JimKillock** [comment] 2014-06-30 16:09
That's done: the page is a near copy - not quite the same content at the page top

**Comment by graphiclunarkid** [comment] 2014-06-30 16:25
Cool - thanks. I'm going to close this and raise the trailing-slash issue as a new issue. If we want to revisit _how_ this is done later (i.e. use @mkillock cleverness rather than duplicating the page) let's do so under a separate issue.

**Closed as completed by graphiclunarkid** 2014-06-30 16:25 UTC
Labels: enhancement, in progress
